import type { Diet, MealLabel, Recipe } from './types';

export interface RecipeEntry extends Recipe {
  diets: Diet[];
  moments: MealLabel[];
  avoidTags: string[]; // matched against profile.avoid
  aisles: Record<string, string[]>; // grocery grouping
}

const ALL: Diet[] = ['omnivore', 'vegetarian', 'vegan', 'pescatarian'];
const VEG: Diet[] = ['omnivore', 'vegetarian', 'pescatarian'];

export const RECIPES: RecipeEntry[] = [
  {
    title: 'Bowl di salmone, riso venere e edamame',
    emoji: '🍣',
    minutes: 20,
    kcal: 610,
    protein: 42,
    carbs: 58,
    fat: 22,
    tagline: 'Omega-3 e crunch, pronta in 20 minuti',
    ingredients: [
      '150 g salmone',
      '70 g riso venere',
      '80 g edamame',
      '½ avocado',
      'Cetriolo, zenzero, salsa di soia',
      'Sesamo tostato',
    ],
    steps: [
      'Cuoci il riso venere in acqua salata (18 min).',
      'Scotta il salmone a cubetti 2 min per lato con un filo di soia.',
      'Componi la bowl: riso, salmone, edamame, avocado e cetriolo.',
      'Chiudi con sesamo e zenzero grattugiato.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Pesce'],
    aisles: {
      Pescheria: ['Salmone fresco 150 g'],
      Dispensa: ['Riso venere', 'Salsa di soia', 'Sesamo'],
      Frigo: ['Edamame surgelati'],
      Ortofrutta: ['Avocado', 'Cetriolo', 'Zenzero'],
    },
  },
  {
    title: 'Pasta di lenticchie, pomodorini e basilico',
    emoji: '🍝',
    minutes: 15,
    kcal: 480,
    protein: 29,
    carbs: 64,
    fat: 11,
    tagline: 'Il comfort food con il doppio delle proteine',
    ingredients: [
      '90 g pasta di lenticchie rosse',
      '200 g pomodorini',
      '1 spicchio d’aglio',
      'Basilico fresco',
      '1 cucchiaio olio EVO',
      'Scaglie di ricotta salata (facoltativa)',
    ],
    steps: [
      'Butta la pasta (cuoce in 7–8 min, non di più).',
      'Salta pomodorini tagliati a metà con aglio e olio per 5 min.',
      'Scola, manteca in padella con un mestolino d’acqua.',
      'Basilico a crudo e, se vuoi, ricotta salata.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: [],
    aisles: {
      Dispensa: ['Pasta di lenticchie rosse', 'Olio EVO'],
      Ortofrutta: ['Pomodorini 200 g', 'Basilico', 'Aglio'],
    },
  },
  {
    title: 'Pollo al limone con patate croccanti',
    emoji: '🍗',
    minutes: 35,
    kcal: 560,
    protein: 48,
    carbs: 42,
    fat: 20,
    tagline: 'Forno, una teglia, zero pensieri',
    ingredients: [
      '180 g sovracosce o petto di pollo',
      '250 g patate novelle',
      '1 limone',
      'Rosmarino e aglio',
      '1 cucchiaio olio EVO',
    ],
    steps: [
      'Forno a 220 °C ventilato.',
      'Patate a spicchi con olio e rosmarino: 15 min in teglia.',
      'Aggiungi il pollo marinato con limone e aglio, altri 18 min.',
      'Ultimo minuto in modalità grill per la crosticina.',
    ],
    diets: ['omnivore'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Carne'],
    aisles: { Macelleria: ['Pollo 180 g'], Ortofrutta: ['Patate novelle', 'Limone', 'Rosmarino'] },
  },
  {
    title: 'Tofu croccante, broccoli e salsa satay',
    emoji: '🥦',
    minutes: 25,
    kcal: 520,
    protein: 32,
    carbs: 38,
    fat: 26,
    tagline: 'Plant-based, ma sazia davvero',
    ingredients: [
      '200 g tofu compatto',
      '250 g broccoli',
      '1 cucchiaio burro d’arachidi',
      'Soia, lime, peperoncino',
      '60 g riso basmati',
    ],
    steps: [
      'Tampona il tofu, taglialo a cubi e infarinalo leggermente con amido.',
      'Rosolalo in padella finché è dorato su tutti i lati.',
      'Broccoli al vapore 5 min, poi saltati con il tofu.',
      'Salsa: burro d’arachidi + soia + lime + acqua calda.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Frutta a guscio'],
    aisles: {
      Frigo: ['Tofu compatto 200 g'],
      Ortofrutta: ['Broccoli', 'Lime', 'Peperoncino'],
      Dispensa: ['Burro d’arachidi', 'Salsa di soia', 'Riso basmati'],
    },
  },
  {
    title: 'Frittata al forno con zucchine e feta',
    emoji: '🍳',
    minutes: 20,
    kcal: 390,
    protein: 28,
    carbs: 9,
    fat: 27,
    tagline: 'Proteine facili, perfetta anche fredda',
    ingredients: ['3 uova', '1 zucchina', '40 g feta', 'Menta fresca', 'Pepe nero'],
    steps: [
      'Forno a 190 °C.',
      'Zucchina a julienne, strizzala bene.',
      'Sbatti le uova con zucchine, feta sbriciolata e menta.',
      'In teglia piccola per 15 min, finché è gonfia e dorata.',
    ],
    diets: VEG,
    moments: ['Pranzo', 'Cena', 'Colazione'],
    avoidTags: ['Uova', 'Lattosio'],
    aisles: { Frigo: ['Uova (3)', 'Feta 40 g'], Ortofrutta: ['Zucchina', 'Menta'] },
  },
  {
    title: 'Overnight oats cacao e lamponi',
    emoji: '🫐',
    minutes: 5,
    kcal: 380,
    protein: 24,
    carbs: 48,
    fat: 10,
    tagline: 'La colazione che ti prepari ieri sera',
    ingredients: [
      '50 g fiocchi d’avena',
      '150 g yogurt greco',
      '100 ml bevanda di soia',
      '1 cucchiaino cacao amaro',
      'Lamponi freschi',
    ],
    steps: [
      'Mescola avena, yogurt, bevanda e cacao in un barattolo.',
      'Chiudi e lascia in frigo tutta la notte.',
      'Al mattino: lamponi sopra e via.',
    ],
    diets: VEG,
    moments: ['Colazione', 'Spuntino'],
    avoidTags: ['Lattosio', 'Glutine'],
    aisles: {
      Dispensa: ['Fiocchi d’avena', 'Cacao amaro'],
      Frigo: ['Yogurt greco', 'Bevanda di soia'],
      Ortofrutta: ['Lamponi'],
    },
  },
  {
    title: 'Toast di segale, hummus e uovo morbido',
    emoji: '🥑',
    minutes: 10,
    kcal: 420,
    protein: 20,
    carbs: 38,
    fat: 20,
    tagline: 'Brunch energy, in dieci minuti',
    ingredients: [
      '2 fette pane di segale',
      '60 g hummus',
      '1 uovo',
      'Rucola',
      'Semi misti, paprika affumicata',
    ],
    steps: [
      'Uovo in acqua bollente per 6 min e 30 s, poi in acqua fredda.',
      'Tosta il pane.',
      'Spalma l’hummus, aggiungi rucola e l’uovo tagliato a metà.',
      'Semi e paprika sopra.',
    ],
    diets: VEG,
    moments: ['Colazione', 'Pranzo', 'Spuntino'],
    avoidTags: ['Uova', 'Glutine'],
    aisles: {
      Panetteria: ['Pane di segale'],
      Frigo: ['Hummus', 'Uova'],
      Ortofrutta: ['Rucola'],
      Dispensa: ['Semi misti', 'Paprika affumicata'],
    },
  },
  {
    title: 'Curry di ceci e spinaci al cocco',
    emoji: '🍛',
    minutes: 25,
    kcal: 540,
    protein: 21,
    carbs: 66,
    fat: 20,
    tagline: 'Speziato, cremoso, 100% vegetale',
    ingredients: [
      '240 g ceci cotti',
      '100 ml latte di cocco light',
      '100 g spinaci',
      '½ cipolla, zenzero, curry',
      '60 g riso basmati',
    ],
    steps: [
      'Soffriggi cipolla e zenzero, aggiungi il curry per 30 s.',
      'Unisci ceci e latte di cocco, sobbolli 10 min.',
      'Spinaci alla fine, giusto il tempo di appassire.',
      'Servi con riso basmati e lime.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: [],
    aisles: {
      Dispensa: ['Ceci cotti', 'Latte di cocco light', 'Curry', 'Riso basmati'],
      Ortofrutta: ['Spinaci', 'Cipolla', 'Zenzero', 'Lime'],
    },
  },
  {
    title: 'Tagliata di manzo, rucola e grana',
    emoji: '🥩',
    minutes: 12,
    kcal: 480,
    protein: 52,
    carbs: 6,
    fat: 27,
    tagline: 'Il classico da trattoria, versione pulita',
    ingredients: [
      '200 g controfiletto',
      'Rucola',
      '20 g scaglie di grana',
      'Pomodorini',
      'Aceto balsamico',
    ],
    steps: [
      'Carne a temperatura ambiente 20 min prima.',
      'Piastra rovente: 2–3 min per lato.',
      'Riposo 5 min, poi taglia a fette.',
      'Su letto di rucola con grana, pomodorini e balsamico.',
    ],
    diets: ['omnivore'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Carne', 'Lattosio'],
    aisles: {
      Macelleria: ['Controfiletto 200 g'],
      Ortofrutta: ['Rucola', 'Pomodorini'],
      Frigo: ['Grana'],
    },
  },
  {
    title: 'Gamberi al lime con couscous alle erbe',
    emoji: '🦐',
    minutes: 15,
    kcal: 450,
    protein: 36,
    carbs: 52,
    fat: 10,
    tagline: 'Fresco, leggero, sa d’estate',
    ingredients: [
      '180 g gamberi sgusciati',
      '70 g couscous',
      'Lime, prezzemolo, menta',
      'Cetriolo e pomodorini',
    ],
    steps: [
      'Couscous con pari peso d’acqua bollente, coperto 5 min.',
      'Gamberi in padella rovente 2 min con aglio e lime.',
      'Sgrana il couscous con erbe, cetriolo e pomodorini.',
      'Gamberi sopra, scorza di lime.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Crostacei', 'Glutine'],
    aisles: {
      Pescheria: ['Gamberi 180 g'],
      Dispensa: ['Couscous'],
      Ortofrutta: ['Lime', 'Prezzemolo', 'Menta', 'Cetriolo', 'Pomodorini'],
    },
  },
  {
    title: 'Skyr bowl con granola e frutti rossi',
    emoji: '🍓',
    minutes: 3,
    kcal: 290,
    protein: 22,
    carbs: 36,
    fat: 6,
    tagline: 'Lo spuntino che chiude il gap di proteine',
    ingredients: ['170 g skyr o yogurt greco', '25 g granola', 'Frutti rossi', 'Cannella'],
    steps: ['Skyr in una ciotola.', 'Frutti rossi e granola sopra.', 'Una spolverata di cannella.'],
    diets: VEG,
    moments: ['Colazione', 'Spuntino'],
    avoidTags: ['Lattosio', 'Glutine'],
    aisles: {
      Frigo: ['Skyr 170 g'],
      Dispensa: ['Granola', 'Cannella'],
      Ortofrutta: ['Frutti rossi'],
    },
  },
  {
    title: 'Edamame al sale affumicato',
    emoji: '🫛',
    minutes: 5,
    kcal: 190,
    protein: 17,
    carbs: 12,
    fat: 8,
    tagline: 'Da sgranocchiare davanti a una serie',
    ingredients: ['150 g edamame surgelati', 'Sale affumicato', 'Peperoncino, lime'],
    steps: [
      'Edamame in acqua bollente 4 min.',
      'Scola e condisci con sale affumicato, peperoncino e lime.',
    ],
    diets: ALL,
    moments: ['Spuntino'],
    avoidTags: [],
    aisles: { Surgelati: ['Edamame 150 g'], Dispensa: ['Sale affumicato'] },
  }, // — added for meal plans: more breakfasts, snacks and everyday mains —
  {
    title: 'Porridge proteico con mela e cannella',
    emoji: '🥣',
    minutes: 8,
    kcal: 420,
    protein: 18,
    carbs: 58,
    fat: 13,
    tagline: 'Caldo, cremoso, ti porta fino a pranzo',
    ingredients: [
      '50 g fiocchi d’avena',
      '250 ml bevanda di soia',
      '1 mela a cubetti',
      '1 cucchiaio di burro di mandorle',
      'Cannella',
    ],
    steps: [
      'Scalda avena e bevanda di soia 4–5 min, mescolando.',
      'Aggiungi metà mela e la cannella a fine cottura.',
      'Completa con la mela rimasta e il burro di mandorle.',
    ],
    diets: ALL,
    moments: ['Colazione'],
    avoidTags: ['Glutine', 'Frutta a guscio'],
    aisles: {
      Dispensa: ['Fiocchi d’avena', 'Burro di mandorle', 'Cannella'],
      Frigo: ['Bevanda di soia'],
      Ortofrutta: ['Mele'],
    },
  },
  {
    title: 'Tofu strapazzato con spinaci e pane integrale',
    emoji: '🍳',
    minutes: 10,
    kcal: 370,
    protein: 24,
    carbs: 30,
    fat: 17,
    tagline: 'L’uovo strapazzato, in versione vegetale',
    ingredients: [
      '150 g tofu',
      '1 manciata di spinaci',
      '1 fetta di pane integrale',
      'Curcuma, paprika, olio EVO',
    ],
    steps: [
      'Sbriciola il tofu in padella con un filo d’olio.',
      'Curcuma e paprika, poi gli spinaci finché appassiscono.',
      'Servi sul pane integrale tostato.',
    ],
    diets: ALL,
    moments: ['Colazione', 'Pranzo'],
    avoidTags: ['Glutine'],
    aisles: {
      Frigo: ['Tofu 150 g'],
      Ortofrutta: ['Spinaci'],
      Panetteria: ['Pane integrale'],
      Dispensa: ['Curcuma', 'Paprika'],
    },
  },
  {
    title: 'Pancake proteici alla banana',
    emoji: '🥞',
    minutes: 12,
    kcal: 400,
    protein: 28,
    carbs: 48,
    fat: 10,
    tagline: 'Colazione della domenica, proteine da giorno feriale',
    ingredients: [
      '1 banana matura',
      '2 uova',
      '40 g farina d’avena',
      '100 g yogurt greco',
      'Cannella',
    ],
    steps: [
      'Schiaccia la banana e frullala con uova e farina d’avena.',
      'Cuoci piccoli pancake in padella antiaderente, 2 min per lato.',
      'Servi con yogurt greco e cannella.',
    ],
    diets: VEG,
    moments: ['Colazione'],
    avoidTags: ['Uova', 'Lattosio', 'Glutine'],
    aisles: {
      Ortofrutta: ['Banane'],
      Frigo: ['Uova', 'Yogurt greco'],
      Dispensa: ['Farina d’avena', 'Cannella'],
    },
  },
  {
    title: 'Yogurt greco, kiwi e semi di chia',
    emoji: '🥝',
    minutes: 3,
    kcal: 270,
    protein: 22,
    carbs: 26,
    fat: 8,
    tagline: 'Fresco, veloce e pieno di proteine',
    ingredients: [
      '200 g yogurt greco 2%',
      '2 kiwi',
      '1 cucchiaio di semi di chia',
      'Un filo di miele',
    ],
    steps: [
      'Yogurt in una ciotola.',
      'Kiwi a rondelle e semi di chia sopra.',
      'Chiudi con un filo di miele.',
    ],
    diets: VEG,
    moments: ['Colazione', 'Spuntino'],
    avoidTags: ['Lattosio'],
    aisles: {
      Frigo: ['Yogurt greco 200 g'],
      Ortofrutta: ['Kiwi'],
      Dispensa: ['Semi di chia', 'Miele'],
    },
  },
  {
    title: 'Toast integrale con ricotta e fragole',
    emoji: '🍓',
    minutes: 5,
    kcal: 320,
    protein: 17,
    carbs: 42,
    fat: 9,
    tagline: 'Dolce senza zuccheri aggiunti (quasi)',
    ingredients: [
      '2 fette di pane integrale',
      '100 g ricotta',
      'Fragole',
      'Menta, un filo di miele',
    ],
    steps: ['Tosta il pane.', 'Spalma la ricotta.', 'Fragole a fette, menta e miele.'],
    diets: VEG,
    moments: ['Colazione', 'Spuntino'],
    avoidTags: ['Glutine', 'Lattosio'],
    aisles: {
      Panetteria: ['Pane integrale'],
      Frigo: ['Ricotta 100 g'],
      Ortofrutta: ['Fragole', 'Menta'],
    },
  },
  {
    title: 'Smoothie bowl banana e frutti rossi',
    emoji: '🫐',
    minutes: 5,
    kcal: 400,
    protein: 14,
    carbs: 60,
    fat: 12,
    tagline: 'Si mangia col cucchiaio, sa di gelato',
    ingredients: [
      '1 banana congelata',
      '100 g frutti rossi',
      '150 ml bevanda di soia',
      '1 cucchiaio di burro d’arachidi',
      'Semi di zucca',
    ],
    steps: [
      'Frulla banana, frutti rossi e bevanda di soia fino a ottenere una crema densa.',
      'Versa in una ciotola.',
      'Completa con burro d’arachidi e semi di zucca.',
    ],
    diets: ALL,
    moments: ['Colazione'],
    avoidTags: ['Frutta a guscio'],
    aisles: {
      Ortofrutta: ['Banane', 'Frutti rossi'],
      Frigo: ['Bevanda di soia'],
      Dispensa: ['Burro d’arachidi', 'Semi di zucca'],
    },
  },
  {
    title: 'Chia pudding con yogurt di soia e mango',
    emoji: '🥭',
    minutes: 5,
    kcal: 340,
    protein: 14,
    carbs: 40,
    fat: 14,
    tagline: 'Si prepara la sera, a colazione è già pronto',
    ingredients: ['25 g semi di chia', '150 g yogurt di soia', '100 ml bevanda di soia', '½ mango'],
    steps: [
      'Mescola semi di chia, yogurt e bevanda di soia.',
      'Lascia in frigo tutta la notte.',
      'Al mattino completa con il mango a cubetti.',
    ],
    diets: ALL,
    moments: ['Colazione', 'Spuntino'],
    avoidTags: [],
    aisles: {
      Dispensa: ['Semi di chia'],
      Frigo: ['Yogurt di soia', 'Bevanda di soia'],
      Ortofrutta: ['Mango'],
    },
  },
  {
    title: 'Hummus e bastoncini di verdure',
    emoji: '🥕',
    minutes: 5,
    kcal: 220,
    protein: 8,
    carbs: 20,
    fat: 12,
    tagline: 'Croccante, saziante, si prepara la sera prima',
    ingredients: ['80 g hummus', 'Carote, sedano, cetriolo', 'Paprika'],
    steps: ['Taglia le verdure a bastoncini.', 'Hummus in una ciotolina con paprika sopra.'],
    diets: ALL,
    moments: ['Spuntino'],
    avoidTags: [],
    aisles: { Frigo: ['Hummus'], Ortofrutta: ['Carote', 'Sedano', 'Cetriolo'] },
  },
  {
    title: 'Mela e mandorle',
    emoji: '🍎',
    minutes: 1,
    kcal: 240,
    protein: 6,
    carbs: 25,
    fat: 13,
    tagline: 'Dolce, croccante, zero sbatti',
    ingredients: ['1 mela', '20 g mandorle'],
    steps: ['Mela a spicchi.', 'Accompagna con le mandorle: fibre e grassi buoni saziano a lungo.'],
    diets: ALL,
    moments: ['Spuntino'],
    avoidTags: ['Frutta a guscio'],
    aisles: { Ortofrutta: ['Mele'], Dispensa: ['Mandorle'] },
  },
  {
    title: 'Banana e burro d’arachidi',
    emoji: '🍌',
    minutes: 1,
    kcal: 260,
    protein: 8,
    carbs: 30,
    fat: 12,
    tagline: 'Il pre-allenamento più semplice che ci sia',
    ingredients: ['1 banana', '1 cucchiaio di burro d’arachidi'],
    steps: ['Banana a rondelle.', 'Un cucchiaio di burro d’arachidi per intingere.'],
    diets: ALL,
    moments: ['Spuntino'],
    avoidTags: ['Frutta a guscio'],
    aisles: { Ortofrutta: ['Banane'], Dispensa: ['Burro d’arachidi'] },
  },
  {
    title: 'Gallette di riso e bresaola',
    emoji: '🥩',
    minutes: 3,
    kcal: 190,
    protein: 18,
    carbs: 22,
    fat: 3,
    tagline: 'Tante proteine, pochissimi grassi',
    ingredients: ['3 gallette di riso', '50 g bresaola', 'Rucola, limone'],
    steps: ['Bresaola sulle gallette.', 'Rucola e qualche goccia di limone.'],
    diets: ['omnivore'],
    moments: ['Spuntino'],
    avoidTags: ['Carne'],
    aisles: {
      Salumeria: ['Bresaola 50 g'],
      Dispensa: ['Gallette di riso'],
      Ortofrutta: ['Rucola', 'Limoni'],
    },
  },
  {
    title: 'Yogurt greco e frutti di bosco',
    emoji: '🫐',
    minutes: 2,
    kcal: 170,
    protein: 15,
    carbs: 16,
    fat: 4,
    tagline: 'Lo spuntino proteico da scrivania',
    ingredients: ['150 g yogurt greco', 'Frutti di bosco', 'Cannella'],
    steps: ['Yogurt in una ciotola, frutti di bosco sopra.', 'Cannella a piacere.'],
    diets: VEG,
    moments: ['Spuntino'],
    avoidTags: ['Lattosio'],
    aisles: { Frigo: ['Yogurt greco 150 g'], Ortofrutta: ['Frutti di bosco'] },
  },
  {
    title: 'Poke di tonno, riso e mango',
    emoji: '🍱',
    minutes: 20,
    kcal: 560,
    protein: 38,
    carbs: 70,
    fat: 14,
    tagline: 'La poke di casa, più proteica di quella da asporto',
    ingredients: [
      '130 g tonno fresco abbattuto',
      '70 g riso basmati',
      '½ mango',
      'Cetriolo, cipollotto',
      'Salsa di soia, sesamo',
    ],
    steps: [
      'Cuoci il riso e lascialo intiepidire.',
      'Tonno a cubetti marinato 5 min con la soia.',
      'Componi con mango, cetriolo e cipollotto.',
      'Sesamo per finire.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Pesce'],
    aisles: {
      Pescheria: ['Tonno fresco 130 g'],
      Dispensa: ['Riso basmati', 'Salsa di soia', 'Sesamo'],
      Ortofrutta: ['Mango', 'Cetriolo', 'Cipollotto'],
    },
  },
  {
    title: 'Pasta integrale al tonno e pomodorini',
    emoji: '🍝',
    minutes: 15,
    kcal: 530,
    protein: 34,
    carbs: 72,
    fat: 12,
    tagline: 'Il pranzo di dispensa che non delude mai',
    ingredients: [
      '80 g pasta integrale',
      '80 g tonno al naturale',
      'Pomodorini, capperi',
      'Olio EVO, prezzemolo',
    ],
    steps: [
      'Cuoci la pasta.',
      'In padella pomodorini e capperi 5 min, poi il tonno a fuoco spento.',
      'Salta la pasta nel sugo con il prezzemolo.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Pesce', 'Glutine'],
    aisles: {
      Dispensa: ['Pasta integrale', 'Tonno al naturale', 'Capperi'],
      Ortofrutta: ['Pomodorini', 'Prezzemolo'],
    },
  },
  {
    title: 'Insalata di farro, ceci e feta',
    emoji: '🥗',
    minutes: 25,
    kcal: 500,
    protein: 22,
    carbs: 62,
    fat: 18,
    tagline: 'Si prepara la sera, a pranzo è ancora più buona',
    ingredients: [
      '70 g farro',
      '100 g ceci cotti',
      '40 g feta',
      'Pomodorini, cetriolo, olive',
      'Olio EVO, origano',
    ],
    steps: [
      'Lessa il farro (20 min) e fallo raffreddare.',
      'Unisci ceci, pomodorini, cetriolo e olive.',
      'Feta sbriciolata, olio e origano.',
    ],
    diets: VEG,
    moments: ['Pranzo'],
    avoidTags: ['Glutine', 'Lattosio'],
    aisles: {
      Dispensa: ['Farro', 'Ceci in barattolo', 'Olive'],
      Frigo: ['Feta'],
      Ortofrutta: ['Pomodorini', 'Cetriolo'],
    },
  },
  {
    title: 'Merluzzo al forno con patate e fagiolini',
    emoji: '🐟',
    minutes: 35,
    kcal: 410,
    protein: 36,
    carbs: 40,
    fat: 11,
    tagline: 'Leggero, profumato, una sola teglia',
    ingredients: [
      '180 g filetto di merluzzo',
      '200 g patate',
      '150 g fagiolini',
      'Limone, prezzemolo, olio EVO',
    ],
    steps: [
      'Patate a spicchi in forno a 200 °C per 20 min.',
      'Aggiungi il merluzzo con limone e prezzemolo, altri 12 min.',
      'Fagiolini lessati 8 min, conditi con olio.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Pesce'],
    aisles: {
      Pescheria: ['Merluzzo 180 g'],
      Ortofrutta: ['Patate', 'Fagiolini', 'Limoni', 'Prezzemolo'],
    },
  },
  {
    title: 'Chili sin carne con riso',
    emoji: '🌶️',
    minutes: 25,
    kcal: 520,
    protein: 24,
    carbs: 82,
    fat: 10,
    tagline: 'Speziato, avvolgente, perfetto da preparare in anticipo',
    ingredients: [
      '120 g fagioli rossi cotti',
      '60 g riso',
      '150 g passata di pomodoro',
      '½ peperone, cipolla',
      'Cumino, paprika affumicata',
    ],
    steps: [
      'Soffriggi cipolla e peperone con le spezie.',
      'Aggiungi fagioli e passata, 15 min a fuoco lento.',
      'Servi con il riso.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: [],
    aisles: {
      Dispensa: ['Fagioli rossi', 'Riso', 'Passata di pomodoro', 'Cumino', 'Paprika affumicata'],
      Ortofrutta: ['Peperoni', 'Cipolle'],
    },
  },
  {
    title: 'Risotto zucca e parmigiano',
    emoji: '🎃',
    minutes: 30,
    kcal: 510,
    protein: 15,
    carbs: 82,
    fat: 14,
    tagline: 'Il comfort food d’autunno',
    ingredients: [
      '80 g riso carnaroli',
      '200 g zucca',
      '20 g parmigiano',
      'Brodo vegetale, scalogno',
      'Rosmarino',
    ],
    steps: [
      'Rosola lo scalogno, aggiungi la zucca a cubetti.',
      'Tosta il riso e portalo a cottura con il brodo (17 min).',
      'Manteca con parmigiano e rosmarino.',
    ],
    diets: VEG,
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Lattosio'],
    aisles: {
      Dispensa: ['Riso carnaroli', 'Brodo vegetale'],
      Ortofrutta: ['Zucca', 'Scalogno', 'Rosmarino'],
      Frigo: ['Parmigiano'],
    },
  },
  {
    title: 'Tacchino, quinoa e verdure grigliate',
    emoji: '🍗',
    minutes: 25,
    kcal: 460,
    protein: 45,
    carbs: 44,
    fat: 11,
    tagline: 'Pulito, colorato, 45 g di proteine',
    ingredients: [
      '150 g fesa di tacchino',
      '60 g quinoa',
      'Zucchine, melanzane, peperoni',
      'Olio EVO, timo',
    ],
    steps: [
      'Cuoci la quinoa (12 min).',
      'Griglia le verdure a fette.',
      'Tacchino in padella 3 min per lato con il timo.',
      'Componi il piatto con un filo d’olio.',
    ],
    diets: ['omnivore'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Carne'],
    aisles: {
      Macelleria: ['Fesa di tacchino 150 g'],
      Dispensa: ['Quinoa'],
      Ortofrutta: ['Zucchine', 'Melanzane', 'Peperoni'],
    },
  },
  {
    title: 'Minestrone con orzo e borlotti',
    emoji: '🥬',
    minutes: 25,
    kcal: 390,
    protein: 14,
    carbs: 62,
    fat: 9,
    tagline: 'Una ciotola calda che sazia con poco',
    ingredients: [
      '300 g minestrone di verdure',
      '50 g orzo perlato',
      '50 g fagioli borlotti cotti',
      'Olio EVO a crudo',
    ],
    steps: [
      'Porta a bollore il minestrone con un po’ d’acqua.',
      'Aggiungi orzo e fagioli, 20 min.',
      'Olio a crudo prima di servire.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Glutine'],
    aisles: { Surgelati: ['Minestrone'], Dispensa: ['Orzo perlato', 'Fagioli borlotti'] },
  },
  {
    title: 'Salmone al forno con patate dolci e spinaci',
    emoji: '🍠',
    minutes: 30,
    kcal: 540,
    protein: 36,
    carbs: 44,
    fat: 24,
    tagline: 'Omega-3 e colore, tutto in forno',
    ingredients: [
      '150 g filetto di salmone',
      '200 g patata dolce',
      'Spinaci novelli',
      'Limone, aneto',
    ],
    steps: [
      'Patata dolce a cubi in forno a 200 °C per 25 min.',
      'Salmone in forno gli ultimi 12 min con limone e aneto.',
      'Servi su un letto di spinaci crudi.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Pesce'],
    aisles: {
      Pescheria: ['Salmone 150 g'],
      Ortofrutta: ['Patate dolci', 'Spinaci', 'Limoni', 'Aneto'],
    },
  },
  {
    title: 'Wrap integrale con pollo e salsa allo yogurt',
    emoji: '🌯',
    minutes: 15,
    kcal: 440,
    protein: 40,
    carbs: 42,
    fat: 12,
    tagline: 'Il pranzo da portare in ufficio',
    ingredients: [
      '1 piadina integrale',
      '120 g petto di pollo',
      '50 g yogurt greco',
      'Lattuga, pomodoro, cetriolo',
      'Paprika, limone',
    ],
    steps: [
      'Pollo a strisce in padella con la paprika, 6 min.',
      'Salsa: yogurt, limone e un pizzico di sale.',
      'Farcisci la piadina con verdure, pollo e salsa.',
    ],
    diets: ['omnivore'],
    moments: ['Pranzo'],
    avoidTags: ['Carne', 'Glutine', 'Lattosio'],
    aisles: {
      Macelleria: ['Petto di pollo 120 g'],
      Panetteria: ['Piadine integrali'],
      Frigo: ['Yogurt greco'],
      Ortofrutta: ['Lattuga', 'Pomodori', 'Cetriolo'],
    },
  },
  {
    title: 'Buddha bowl con tempeh e tahina',
    emoji: '🥙',
    minutes: 25,
    kcal: 530,
    protein: 30,
    carbs: 58,
    fat: 20,
    tagline: 'Proteine vegetali, crunch e una salsa che crea dipendenza',
    ingredients: [
      '100 g tempeh',
      '60 g riso integrale',
      'Cavolo rosso, carote, edamame',
      'Salsa tahina e limone',
    ],
    steps: [
      'Cuoci il riso integrale.',
      'Tempeh a cubetti in padella con la soia, 5 min.',
      'Componi con le verdure crude e la tahina.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: [],
    aisles: {
      Frigo: ['Tempeh 100 g'],
      Dispensa: ['Riso integrale', 'Tahina', 'Salsa di soia'],
      Ortofrutta: ['Cavolo rosso', 'Carote'],
      Surgelati: ['Edamame'],
    },
  },
  {
    title: 'Uova in purgatorio con pane casereccio',
    emoji: '🍅',
    minutes: 15,
    kcal: 370,
    protein: 20,
    carbs: 32,
    fat: 18,
    tagline: 'Una padella, dieci minuti, scarpetta obbligatoria',
    ingredients: [
      '2 uova',
      '200 g passata di pomodoro',
      '1 fetta di pane casereccio',
      'Basilico, olio EVO',
    ],
    steps: [
      'Scalda la passata con olio e basilico, 5 min.',
      'Apri le uova nel sugo, coperchio, 6 min.',
      'Servi con il pane per la scarpetta.',
    ],
    diets: VEG,
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Uova', 'Glutine'],
    aisles: {
      Frigo: ['Uova'],
      Dispensa: ['Passata di pomodoro'],
      Panetteria: ['Pane casereccio'],
      Ortofrutta: ['Basilico'],
    },
  },
];

export function findRecipe(text: string): RecipeEntry | undefined {
  const t = text.toLowerCase();
  return (
    RECIPES.find((r) => t.includes(r.title.toLowerCase())) ??
    RECIPES.find((r) => {
      const words = r.title
        .toLowerCase()
        .split(/[ ,]+/)
        .filter((w) => w.length > 4);
      return words.filter((w) => t.includes(w)).length >= 2;
    })
  );
}
