import type { Diet, MealLabel, Recipe } from './types';

export interface RecipeEntry extends Recipe {
  diets: Diet[];
  moments: MealLabel[];
  avoidTags: string[]; // matched against profile.avoid
  aisles: Record<string, string[]>; // grocery grouping
}

const ALL: Diet[] = ['omnivore', 'vegetarian', 'vegan', 'pescatarian'];
const VEG: Diet[] = ['omnivore', 'vegetarian', 'pescatarian'];

export const RECIPES: RecipeEntry[] = [
  {
    title: 'Bowl di salmone, riso venere e edamame',
    emoji: '🍣',
    minutes: 20,
    kcal: 610,
    protein: 42,
    carbs: 58,
    fat: 22,
    tagline: 'Omega-3 e crunch, pronta in 20 minuti',
    ingredients: [
      '150 g salmone',
      '70 g riso venere',
      '80 g edamame',
      '½ avocado',
      'Cetriolo, zenzero, salsa di soia',
      'Sesamo tostato',
    ],
    steps: [
      'Cuoci il riso venere in acqua salata (18 min).',
      'Scotta il salmone a cubetti 2 min per lato con un filo di soia.',
      'Componi la bowl: riso, salmone, edamame, avocado e cetriolo.',
      'Chiudi con sesamo e zenzero grattugiato.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Pesce'],
    aisles: {
      Pescheria: ['Salmone fresco 150 g'],
      Dispensa: ['Riso venere', 'Salsa di soia', 'Sesamo'],
      Frigo: ['Edamame surgelati'],
      Ortofrutta: ['Avocado', 'Cetriolo', 'Zenzero'],
    },
  },
  {
    title: 'Pasta di lenticchie, pomodorini e basilico',
    emoji: '🍝',
    minutes: 15,
    kcal: 480,
    protein: 29,
    carbs: 64,
    fat: 11,
    tagline: 'Il comfort food con il doppio delle proteine',
    ingredients: [
      '90 g pasta di lenticchie rosse',
      '200 g pomodorini',
      '1 spicchio d’aglio',
      'Basilico fresco',
      '1 cucchiaio olio EVO',
      'Scaglie di ricotta salata (facoltativa)',
    ],
    steps: [
      'Butta la pasta (cuoce in 7–8 min, non di più).',
      'Salta pomodorini tagliati a metà con aglio e olio per 5 min.',
      'Scola, manteca in padella con un mestolino d’acqua.',
      'Basilico a crudo e, se vuoi, ricotta salata.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: [],
    aisles: {
      Dispensa: ['Pasta di lenticchie rosse', 'Olio EVO'],
      Ortofrutta: ['Pomodorini 200 g', 'Basilico', 'Aglio'],
    },
  },
  {
    title: 'Pollo al limone con patate croccanti',
    emoji: '🍗',
    minutes: 35,
    kcal: 560,
    protein: 48,
    carbs: 42,
    fat: 20,
    tagline: 'Forno, una teglia, zero pensieri',
    ingredients: [
      '180 g sovracosce o petto di pollo',
      '250 g patate novelle',
      '1 limone',
      'Rosmarino e aglio',
      '1 cucchiaio olio EVO',
    ],
    steps: [
      'Forno a 220 °C ventilato.',
      'Patate a spicchi con olio e rosmarino: 15 min in teglia.',
      'Aggiungi il pollo marinato con limone e aglio, altri 18 min.',
      'Ultimo minuto in modalità grill per la crosticina.',
    ],
    diets: ['omnivore'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Carne'],
    aisles: { Macelleria: ['Pollo 180 g'], Ortofrutta: ['Patate novelle', 'Limone', 'Rosmarino'] },
  },
  {
    title: 'Tofu croccante, broccoli e salsa satay',
    emoji: '🥦',
    minutes: 25,
    kcal: 520,
    protein: 32,
    carbs: 38,
    fat: 26,
    tagline: 'Plant-based, ma sazia davvero',
    ingredients: [
      '200 g tofu compatto',
      '250 g broccoli',
      '1 cucchiaio burro d’arachidi',
      'Soia, lime, peperoncino',
      '60 g riso basmati',
    ],
    steps: [
      'Tampona il tofu, taglialo a cubi e infarinalo leggermente con amido.',
      'Rosolalo in padella finché è dorato su tutti i lati.',
      'Broccoli al vapore 5 min, poi saltati con il tofu.',
      'Salsa: burro d’arachidi + soia + lime + acqua calda.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Frutta a guscio'],
    aisles: {
      Frigo: ['Tofu compatto 200 g'],
      Ortofrutta: ['Broccoli', 'Lime', 'Peperoncino'],
      Dispensa: ['Burro d’arachidi', 'Salsa di soia', 'Riso basmati'],
    },
  },
  {
    title: 'Frittata al forno con zucchine e feta',
    emoji: '🍳',
    minutes: 20,
    kcal: 390,
    protein: 28,
    carbs: 9,
    fat: 27,
    tagline: 'Proteine facili, perfetta anche fredda',
    ingredients: ['3 uova', '1 zucchina', '40 g feta', 'Menta fresca', 'Pepe nero'],
    steps: [
      'Forno a 190 °C.',
      'Zucchina a julienne, strizzala bene.',
      'Sbatti le uova con zucchine, feta sbriciolata e menta.',
      'In teglia piccola per 15 min, finché è gonfia e dorata.',
    ],
    diets: VEG,
    moments: ['Pranzo', 'Cena', 'Colazione'],
    avoidTags: ['Uova', 'Lattosio'],
    aisles: { Frigo: ['Uova (3)', 'Feta 40 g'], Ortofrutta: ['Zucchina', 'Menta'] },
  },
  {
    title: 'Overnight oats cacao e lamponi',
    emoji: '🫐',
    minutes: 5,
    kcal: 380,
    protein: 24,
    carbs: 48,
    fat: 10,
    tagline: 'La colazione che ti prepari ieri sera',
    ingredients: [
      '50 g fiocchi d’avena',
      '150 g yogurt greco',
      '100 ml bevanda di soia',
      '1 cucchiaino cacao amaro',
      'Lamponi freschi',
    ],
    steps: [
      'Mescola avena, yogurt, bevanda e cacao in un barattolo.',
      'Chiudi e lascia in frigo tutta la notte.',
      'Al mattino: lamponi sopra e via.',
    ],
    diets: VEG,
    moments: ['Colazione', 'Spuntino'],
    avoidTags: ['Lattosio', 'Glutine'],
    aisles: {
      Dispensa: ['Fiocchi d’avena', 'Cacao amaro'],
      Frigo: ['Yogurt greco', 'Bevanda di soia'],
      Ortofrutta: ['Lamponi'],
    },
  },
  {
    title: 'Toast di segale, hummus e uovo morbido',
    emoji: '🥑',
    minutes: 10,
    kcal: 420,
    protein: 20,
    carbs: 38,
    fat: 20,
    tagline: 'Brunch energy, in dieci minuti',
    ingredients: [
      '2 fette pane di segale',
      '60 g hummus',
      '1 uovo',
      'Rucola',
      'Semi misti, paprika affumicata',
    ],
    steps: [
      'Uovo in acqua bollente per 6 min e 30 s, poi in acqua fredda.',
      'Tosta il pane.',
      'Spalma l’hummus, aggiungi rucola e l’uovo tagliato a metà.',
      'Semi e paprika sopra.',
    ],
    diets: VEG,
    moments: ['Colazione', 'Pranzo', 'Spuntino'],
    avoidTags: ['Uova', 'Glutine'],
    aisles: {
      Panetteria: ['Pane di segale'],
      Frigo: ['Hummus', 'Uova'],
      Ortofrutta: ['Rucola'],
      Dispensa: ['Semi misti', 'Paprika affumicata'],
    },
  },
  {
    title: 'Curry di ceci e spinaci al cocco',
    emoji: '🍛',
    minutes: 25,
    kcal: 540,
    protein: 21,
    carbs: 66,
    fat: 20,
    tagline: 'Speziato, cremoso, 100% vegetale',
    ingredients: [
      '240 g ceci cotti',
      '100 ml latte di cocco light',
      '100 g spinaci',
      '½ cipolla, zenzero, curry',
      '60 g riso basmati',
    ],
    steps: [
      'Soffriggi cipolla e zenzero, aggiungi il curry per 30 s.',
      'Unisci ceci e latte di cocco, sobbolli 10 min.',
      'Spinaci alla fine, giusto il tempo di appassire.',
      'Servi con riso basmati e lime.',
    ],
    diets: ALL,
    moments: ['Pranzo', 'Cena'],
    avoidTags: [],
    aisles: {
      Dispensa: ['Ceci cotti', 'Latte di cocco light', 'Curry', 'Riso basmati'],
      Ortofrutta: ['Spinaci', 'Cipolla', 'Zenzero', 'Lime'],
    },
  },
  {
    title: 'Tagliata di manzo, rucola e grana',
    emoji: '🥩',
    minutes: 12,
    kcal: 480,
    protein: 52,
    carbs: 6,
    fat: 27,
    tagline: 'Il classico da trattoria, versione pulita',
    ingredients: [
      '200 g controfiletto',
      'Rucola',
      '20 g scaglie di grana',
      'Pomodorini',
      'Aceto balsamico',
    ],
    steps: [
      'Carne a temperatura ambiente 20 min prima.',
      'Piastra rovente: 2–3 min per lato.',
      'Riposo 5 min, poi taglia a fette.',
      'Su letto di rucola con grana, pomodorini e balsamico.',
    ],
    diets: ['omnivore'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Carne', 'Lattosio'],
    aisles: {
      Macelleria: ['Controfiletto 200 g'],
      Ortofrutta: ['Rucola', 'Pomodorini'],
      Frigo: ['Grana'],
    },
  },
  {
    title: 'Gamberi al lime con couscous alle erbe',
    emoji: '🦐',
    minutes: 15,
    kcal: 450,
    protein: 36,
    carbs: 52,
    fat: 10,
    tagline: 'Fresco, leggero, sa d’estate',
    ingredients: [
      '180 g gamberi sgusciati',
      '70 g couscous',
      'Lime, prezzemolo, menta',
      'Cetriolo e pomodorini',
    ],
    steps: [
      'Couscous con pari peso d’acqua bollente, coperto 5 min.',
      'Gamberi in padella rovente 2 min con aglio e lime.',
      'Sgrana il couscous con erbe, cetriolo e pomodorini.',
      'Gamberi sopra, scorza di lime.',
    ],
    diets: ['omnivore', 'pescatarian'],
    moments: ['Pranzo', 'Cena'],
    avoidTags: ['Crostacei', 'Glutine'],
    aisles: {
      Pescheria: ['Gamberi 180 g'],
      Dispensa: ['Couscous'],
      Ortofrutta: ['Lime', 'Prezzemolo', 'Menta', 'Cetriolo', 'Pomodorini'],
    },
  },
  {
    title: 'Skyr bowl con granola e frutti rossi',
    emoji: '🍓',
    minutes: 3,
    kcal: 290,
    protein: 22,
    carbs: 36,
    fat: 6,
    tagline: 'Lo spuntino che chiude il gap di proteine',
    ingredients: ['170 g skyr o yogurt greco', '25 g granola', 'Frutti rossi', 'Cannella'],
    steps: ['Skyr in una ciotola.', 'Frutti rossi e granola sopra.', 'Una spolverata di cannella.'],
    diets: VEG,
    moments: ['Colazione', 'Spuntino'],
    avoidTags: ['Lattosio', 'Glutine'],
    aisles: {
      Frigo: ['Skyr 170 g'],
      Dispensa: ['Granola', 'Cannella'],
      Ortofrutta: ['Frutti rossi'],
    },
  },
  {
    title: 'Edamame al sale affumicato',
    emoji: '🫛',
    minutes: 5,
    kcal: 190,
    protein: 17,
    carbs: 12,
    fat: 8,
    tagline: 'Da sgranocchiare davanti a una serie',
    ingredients: ['150 g edamame surgelati', 'Sale affumicato', 'Peperoncino, lime'],
    steps: [
      'Edamame in acqua bollente 4 min.',
      'Scola e condisci con sale affumicato, peperoncino e lime.',
    ],
    diets: ALL,
    moments: ['Spuntino'],
    avoidTags: [],
    aisles: { Surgelati: ['Edamame 150 g'], Dispensa: ['Sale affumicato'] },
  },
];

export function findRecipe(text: string): RecipeEntry | undefined {
  const t = text.toLowerCase();
  return (
    RECIPES.find((r) => t.includes(r.title.toLowerCase())) ??
    RECIPES.find((r) => {
      const words = r.title
        .toLowerCase()
        .split(/[ ,]+/)
        .filter((w) => w.length > 4);
      return words.filter((w) => t.includes(w)).length >= 2;
    })
  );
}
