// Extracts the Solar icons Nouri uses from @iconify-json/solar into a small
// generated module, so the app ships only these SVGs (no icon font, no runtime dep).
// Run with: bun run icons
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const set = JSON.parse(readFileSync(require.resolve('@iconify-json/solar/icons.json'), 'utf8'));

const ICONS = [
  // plan & profile
  'graph-down-new-bold-duotone',
  'bolt-bold-duotone',
  'dumbbell-large-minimalistic-bold-duotone',
  'heart-pulse-bold-duotone',
  'chef-hat-bold-duotone',
  'leaf-bold-duotone',
  'hand-heart-bold-duotone',
  'water-bold-duotone',
  'sofa-2-bold-duotone',
  'walking-bold-duotone',
  'running-bold-duotone',
  'forbidden-circle-bold-duotone',
  'scale-bold-duotone',
  'waterdrops-bold-duotone',
  'waterdrop-bold-duotone',
  'target-bold-duotone',
  'fire-bold-duotone',
  'cpu-bolt-bold-duotone',
  'volume-loud-bold-duotone',
  'magic-stick-3-bold-duotone',
  'trash-bin-trash-bold-duotone',
  'restart-bold-duotone',
  'user-rounded-bold-duotone',
  'settings-bold-duotone',
  // menus & actions
  'pen-new-square-bold-duotone',
  'notebook-bold-duotone',
  'chart-2-bold-duotone',
  'chef-hat-heart-bold-duotone',
  'cart-large-2-bold-duotone',
  'soundwave-bold-duotone',
  'camera-bold-duotone',
  'gallery-bold-duotone',
  'plate-bold-duotone',
  'stopwatch-bold-duotone',
  'pie-chart-2-bold-duotone',
  'chat-round-dots-bold-duotone',
  'copy-bold-duotone',
  'refresh-bold-duotone',
  'info-circle-bold-duotone',
  'check-circle-bold-duotone',
  'danger-triangle-bold-duotone',
  'lightbulb-bolt-bold-duotone',
  // memory, quick search, meal plan
  'brain-bold-duotone',
  'heart-bold-duotone',
  'dislike-bold-duotone',
  'notebook-minimalistic-bold-duotone',
  'bolt-circle-bold-duotone',
  'bookmark-bold-duotone',
  'magnifer-bold-duotone',
  'barcode-scan-bold-duotone',
  'box-bold-duotone',
  'calendar-bold-duotone',
  'calendar-add-bold-duotone',
  'shuffle-bold-duotone',
  'clipboard-list-bold-duotone',
  'tuning-bold-duotone',
  // chrome (linear / bold)
  'hamburger-menu-linear',
  'pen-new-square-linear',
  'add-linear',
  'minus-linear',
  'arrow-up-linear',
  'close-linear',
  'alt-arrow-right-linear',
  'alt-arrow-down-linear',
  'alt-arrow-left-linear',
  'soundwave-linear',
  'microphone-3-bold',
  'stop-bold',
  'check-linear',
  'copy-linear',
  'volume-loud-linear',
  'check-circle-bold',
  'menu-dots-bold',
  'keyboard-linear',
  'settings-linear',
  'trash-bin-minimalistic-linear',
  'camera-linear',
  'gallery-linear',
  'barcode-scan-linear',
  'bookmark-linear',
  'calendar-linear',
  'history-linear',
  'close-circle-bold',
  'undo-left-linear',
  'flashlight-on-linear',
  'flashlight-linear',
  'add-circle-linear',
];

// Solar has no plain linear magnifier: the line-duotone one is flattened to a single tone.
const DERIVED = {
  'magnifer-linear': [
    'magnifer-line-duotone',
    (body) => body.replace(/stroke="gray"/g, 'stroke="#fff"'),
  ],
};

const missing = [...ICONS, ...Object.values(DERIVED).map(([from]) => from)].filter(
  (n) => !set.icons[n]
);
if (missing.length) throw new Error(`Unknown Solar icons: ${missing.join(', ')}`);

const lines = [
  ...ICONS.map((n) => `  '${n}': ${JSON.stringify(set.icons[n].body)},`),
  ...Object.entries(DERIVED).map(
    ([name, [from, fn]]) => `  '${name}': ${JSON.stringify(fn(set.icons[from].body))},`
  ),
];
const out = `// Generated by scripts/build-icons.mjs from @iconify-json/solar (CC BY 4.0, 480 Design).
// Do not edit by hand: add the icon name to the script and run \`bun run icons\`.
export const SOLAR = {
${lines.join('\n')}
} as const;

export type SolarName = keyof typeof SOLAR;
`;
writeFileSync(new URL('../components/ui/solar-icons.ts', import.meta.url), out);
console.log(`wrote ${lines.length} icons`);
